---
retropie:
    romfilter:
        trashPath: "/home/pi/RetroPie/roms/.trash"
        systemsIndexPath: "./romfilter-systems.index"
        gamesIndexPath: "./romfilter-games.index"
        romsIndexPath: "./romfilter-roms.index"
        skipSystems:
        - retropie

    emulationStation:
        romsPath: "/home/pi/RetroPie/roms"
        gamelistsPath: "/home/pi/.emulationstation/gamelists"
        imagesPath: "/home/pi/.emulationstation/downloaded_images"
        imagesPrefix: "~/.emulationstation/downloaded_images/"
        system:
            3do:
                validRomTypes:
                - 'iso'
            amiga:
                validRomTypes:
                - 'asf'
                - 'zip'
                - 'dms'
                - 'exe'
                - 'adz'
                - 'rp9'
            atari2600:
                validRomTypes:
                - 'bin'
                - 'a26'
                - 'rom'
                - 'zip'
                - 'gz'
            n64:
                validRomTypes:
                - 'n64'
                - 'v64'
                - 'z64'
            nes:
                validRomTypes:
                - 'zip'
                - 'nes'
                - 'smc'
                - 'sfc'
                - 'fig'
                - 'swc'
                - 'mgd'
                - 'fds'
            snes:
                validRomTypes:
                - 'zip'
                - 'smc'
                - 'sfc'
                - 'fig'
                - 'swc'

---
quartz:
    autoStartup: true
    jdbcStore: false

environments:
    test:
        quartz:
            autoStartup: false
        retropie:
            romfilter:
                trashPath: "./build/resources/test/integration/trash"
                systemsIndexPath: "./build/resources/test/integration/indexes/romfilter-systems.index"
                gamesIndexPath: "./build/resources/test/integration/indexes/romfilter-games.index"
                romsIndexPath: "./build/resources/test/integration/indexes/romfilter-roms.index"
            emulationStation:
                romsPath: "./build/resources/test/integration/roms"
                gamelistsPath: "./build/resources/test/integration/gamelists"
                imagesPath: "./build/resources/test/integration/downloaded_images"

---
grails:
    profile: web
    codegen:
        defaultPackage: retropie.romfilter
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
